repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]

      # check for file bigger than 500kb
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/Trim21/find-trailing-comma
    rev: v0.0.1
    hooks:
      - id: find-trailing-comma

#  isort in pre-commit don't read config file in setup.cfg
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.21  # Use the revision sha / tag you want to point at
#    hooks:
#      - id: isort
#        additional_dependencies: ['toml==0.10.0']

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
      - id: pyupgrade
        args: ['--py36-plus',]

  - repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc2
    hooks:
      - id: doc8
        args: [ '--max-line-length', '88', '--file-encoding', 'utf-8' ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9  # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies:
          - flake8-comprehensions==3.1.4
          - flake8-comprehensions==3.1.4
          - flake8-bugbear==19.8.0
          - flake8-commas==2.0.0
          - flake8-mutable==1.2.0

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: '0.750'  # Use the sha / tag you want to point at
#    hooks:
#      - id: mypy

  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: yapf -i
        require_serial: true
        language: system
        types: [python]

#      - id: flake8
#        name: flake8
#        entry: flake8
#        language: system
#        types: [python]
#        args: ['--config=setup.cfg']

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types: [python]

      - id: autoflake
        name: autoflake
        entry: autoflake
        require_serial: true
        language: system
        types: [python]
        args: ['--in-place',
               '--remove-unused-variables',
               '--remove-all-unused-imports']
